CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS patient_db;
CREATE DATABASE IF NOT EXISTS inventory_db;
CREATE DATABASE IF NOT EXISTS billing;
CREATE DATABASE IF NOT EXISTS medlab;
CREATE DATABASE IF NOT EXISTS lab_processing;
CREATE DATABASE IF NOT EXISTS notification_db;
