server:
  port: 8084

spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: thisisverysecuresecretkeyforjwttokengenerationandvalidationteam5medlab
    # Must be the SAME secret key used in the User Service
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html